#!/bin/bash
#get script dir
get_script_dir() {
    echo "$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
}

#Check if we are in the test directory
TEST_DIR="$(pwd)"
METADATA_FILE="$TEST_DIR/metadata.yaml"
SCRIPT_DIR=$(get_script_dir)
PYTHON_SCRIPT="$SCRIPT_DIR/preprocess.py"
HISTORY_FILE="$TEST_DIR/outputs/output_his.nc"

# Check if the script exists
if [[ ! -f "$PYTHON_SCRIPT" ]]; then
    echo "Error: Python script not found at $PYTHON_SCRIPT."
    exit 1
fi

# Check if metadata.yaml exists
if [[ ! -f "$METADATA_FILE" ]]; then
    echo "Error: Metadata not found. Please run the script from a test directory."
    exit 1
fi

# Check if history file exists
if [[ ! -f "$HISTORY_FILE" ]]; then
    echo "Error: History file not found. Please run the simulation first."
    exit 1
fi

# Check if the history file has already been preprocessed
if [[ -f "$TEST_DIR/outputs/output_his_preprocessed.nc" ]]; then
    echo "History file has already been preprocessed."
    exit 0
fi




# Run the script
python3 "$PYTHON_SCRIPT" "$HISTORY_FILE"
