#!/bin/bash

# Check if metadata.yaml exists
if [[ ! -f "metadata.yaml" ]]; then
    echo "Error: metadata.yaml not found. This script must be run from within a test directory."
    exit 1
fi

# Read dependencies from metadata.yaml
DEPENDENCIES=$(jq -r '.dependencies | .[]' "metadata.yaml")
# Read parent dependencies from ../../metadata.yaml
PARENT_DEPENDENCIES=$(jq -r '.dependencies | .[]' "../../metadata.yaml")

# Convert parent dependencies into an array
IFS=$'\n' read -rd '' -a PARENT_DEPENDENCIES_ARRAY <<< "$PARENT_DEPENDENCIES"

# Loop through dependencies and check against parent dependencies
for DEPENDENCY in $DEPENDENCIES; do

    # Use a flag to track if the dependency is found
    FOUND=false
    for PARENT_DEPENDENCY in "${PARENT_DEPENDENCIES_ARRAY[@]}"; do
        if [[ "$PARENT_DEPENDENCY" == "$DEPENDENCY" ]]; then
            FOUND=true
            break
        fi
    done

    if [[ "$FOUND" == false ]]; then
        echo "Error: Dependency '$DEPENDENCY' not found in parent test."
        exit 1
    fi

    # Print difference between dependencies only if a dependency is missing
    if [[ "$FOUND" == false ]]; then
        echo "Difference between dependencies"
        DIFFERENCE=$(diff <(echo "$DEPENDENCIES" | tr ' ' '\n' | sort) <(echo "$PARENT_DEPENDENCIES" | tr ' ' '\n' | sort))
        echo "$DIFFERENCE"
    fi


done
