Resolutions:
  hires:
    input_grd: "Resolutions/hires/input_grd.nc"
    input_frc: "Resolutions/hires/input_frc.nc"
    param: "Resolutions/hires/param.h"
    infile: "Resolutions/hires/infile.in"
  medres:
    input_grd: "Resolutions/medres/input_grd.nc"
    input_frc: "Resolutions/medres/input_frc.nc"
    param: "Resolutions/medres/param.h"
    infile: "Resolutions/medres/infile.in"
  lowres:
    param: "Resolutions/lowres/param.h"
    infile: "Resolutions/lowres/infile.in"

InitialConditions:
  Config1:
    input_rst_hires: "InitialConditions/Config1/input_rst_hires.nc"
    input_rst_medres: "InitialConditions/Config1/input_rst_medres.nc"
    Description: "InitialConditions/Config1/Description.txt"

Diffusion:
  Control:
    t3dmix_S: "Diffusion/t3dmix_S_Control.F"
  EHDA:
    t3dmix_S: "Diffusion/t3dmix_S_EHDA.F"
  EHDB:
    t3dmix_S: "Diffusion/t3dmix_S_EHDB.F"

BaseFiles:
  jobcomp: "BaseFiles/jobcomp"
  cppdefs_biology: "BaseFiles/cppdefs_biology.h"
  cppdefs_physics: "BaseFiles/cppdefs_physics.h"

FileDestinations:
  Grid: "inputs/input_grd.nc"
  Forcing: "inputs/input_frc.nc"
  Restart: "inputs/input_rst.nc"
  Infile: "inputs/infile.in"
  ConfigDescription: "inputs/init_description.txt"
  Param: "dependencies/param.h"
  Cppdefs: "dependencies/cppdefs.h"
  Diffusion: "dependencies/t3dmix_S.F"
  CompilationScript: "jobcomp"
