Resolutions:
  hires:
    input_grd: "Resolutions/hires/input_grd.nc"
    input_frc: "Resolutions/hires/input_frc.nc"
    cppdefs_biology: "Resolutions/hires/cppdefs_biology.h"
    cppdefs_physics: "Resolutions/hires/cppdefs_physics.h"
    param: "Resolutions/hires/param.h"
  medres:
    input_grd: "Resolutions/medres/input_grd.nc"
    input_frc: "Resolutions/medres/input_frc.nc"
    cppdefs_biology: "Resolutions/medres/cppdefs_biology.h"
    cppdefs_physics: "Resolutions/medres/cppdefs_physics.h"
    param: "Resolutions/medres/param.h"
  lowres:
    input_grd: "Resolutions/lowres/input_grd.nc"
    input_frc: "Resolutions/lowres/input_frc.nc"
    cppdefs_biology: "Resolutions/lowres/cppdefs_biology.h"
    cppdefs_physics: "Resolutions/lowres/cppdefs_physics.h"
    param: "Resolutions/lowres/param.h"


InitialConditions:
  Config1:
    input_rst_hires: "InitialConditions/Config1/input_rst_hires.nc"
    input_rst_medres: "InitialConditions/Config1/input_rst_medres.nc"
    input_rst_lowres: "InitialConditions/Config1/input_rst_lowres.nc"
    infile_hires: "InitialConditions/Config1/infile_hires.in"
    infile_medres: "InitialConditions/Config1/infile_medres.in"
    infile_lowres: "InitialConditions/Config1/infile_lowres.in"
    Description: "InitialConditions/Config1/Description.txt"
  Config2:
    input_rst_hires: "InitialConditions/Config2/input_rst_hires.nc"
    input_rst_medres: "InitialConditions/Config2/input_rst_medres.nc"
    input_rst_lowres: "InitialConditions/Config2/input_rst_lowres.nc"
    infile_hires: "InitialConditions/Config2/infile_hires.in"
    infile_medres: "InitialConditions/Config2/infile_medres.in"
    infile_lowres: "InitialConditions/Config2/infile_lowres.in"
    Description: "InitialConditions/Config2/Description.txt"
  Config3:
    input_rst_hires: "InitialConditions/Config3/input_rst_hires.nc"
    input_rst_medres: "InitialConditions/Config3/input_rst_medres.nc"
    input_rst_lowres: "InitialConditions/Config3/input_rst_lowres.nc"
    infile_hires: "InitialConditions/Config3/infile_hires.in"
    infile_medres: "InitialConditions/Config3/infile_medres.in"
    infile_lowres: "InitialConditions/Config3/infile_lowres.in"
    Description: "InitialConditions/Config3/Description.txt"
  Config4:
    input_rst_hires: "InitialConditions/Config4/input_rst_hires.nc"
    input_rst_medres: "InitialConditions/Config4/input_rst_medres.nc"
    input_rst_lowres: "InitialConditions/Config4/input_rst_lowres.nc"
    infile_hires: "InitialConditions/Config4/infile_hires.in"
    infile_medres: "InitialConditions/Config4/infile_medres.in"
    infile_lowres: "InitialConditions/Config4/infile_lowres.in"
    Description: "InitialConditions/Config4/Description.txt"
  Config5:
    input_rst_hires: "InitialConditions/Config5/input_rst_hires.nc"
    input_rst_medres: "InitialConditions/Config5/input_rst_medres.nc"
    input_rst_lowres: "InitialConditions/Config5/input_rst_lowres.nc"
    infile_hires: "InitialConditions/Config5/infile_hires.in"
    infile_medres: "InitialConditions/Config5/infile_medres.in"
    infile_lowres: "InitialConditions/Config5/infile_lowres.in"
    Description: "InitialConditions/Config5/Description.txt"

Diffusion:
  Control:
    t3dmix_S: "Diffusion/t3dmix_S_Control.F"
  EHDA:
    t3dmix_S: "Diffusion/t3dmix_S_EHDA.F"
  EHDB:
    t3dmix_S: "Diffusion/t3dmix_S_EHDB.F"

Biology: "bio_NChlPZD.F"
    

FileDestinations:
  Grid: "inputs/input_grd.nc"
  Forcing: "inputs/input_frc.nc"
  Restart: "inputs/input_rst.nc"
  Infile: "inputs/infile.in"
  ConfigDescription: "inputs/init_description.txt"
  Param: "dependencies/param.h"
  Cppdefs: "dependencies/cppdefs.h"
  Diffusion: "dependencies/t3dmix_S.F"
  Biology: "dependencies/bio_NChlPZD.F"